from selenium.webdriver.common.by import By


class BasePageLocators():
    CITY_POPUP_YES_BUTTON = (By.CSS_SELECTOR, ".prmn-cmngr__confirm-btn.btn-primary")
    CITY_NAME_IN_HEADER = (By.CSS_SELECTOR, ".prmn-cmngr__city")
    FIRST_CITY_NAME_IN_CITY_MENU = (By.CSS_SELECTOR, "a.prmn-cmngr-cities__city-name")
    DESKTOP_CALLBACK_FORM = (By.CSS_SELECTOR, ".fly_callback")
    DESKTOP_CALLBACK_FORM_NAME_FIELD = (By.XPATH, "//input[@name='customer_name']")
    DESKTOP_CALLBACK_FORM_PHONE_FIELD = (By.XPATH, "//input[@name='customer_phone']")
    CALLBACK_FORM_POLICY_CHECKBOX = (By.CSS_SELECTOR, ".radio")
    CONTACT_SENT_BUTTON = (By.CSS_SELECTOR, "button.callback_button")
    SENT_MESSAGE_WINDOW = (By.CSS_SELECTOR, ".callback_success")
    HEADER_SEARCH_FIELD = (By.CSS_SELECTOR, "#div_search .form-control")
    HEADER_SEARCH_BUTTON = (By.CSS_SELECTOR, "#div_search button.search")
    PRODUCT_CARD = (By.CSS_SELECTOR, ".product-layout")
    ACCOUNT_LINK = (By.CSS_SELECTOR, ".dropdown-toggle .hidden-xs")
    REGISTER_LINK = (By.XPATH, "//a[@onclick='register();']")
    REGISTER_NAME = (By.XPATH, "//input[@name='firstname']")
    REGISTER_SURNAME = (By.XPATH, "//input[@name='lastname']")
    REGISTER_PHONE = (By.XPATH, "//input[@name='telephone']")
    REGISTER_EMAIL = (By.CSS_SELECTOR, "div#popup_register input[name='email']")
    REGISTER_PASSWORD = (By.CSS_SELECTOR, "div#popup_register input[name='password']")
    REGISTER_FORM_PRIVACY_CHECKBOX = (By.CSS_SELECTOR, "label.input span")
    REGISTER_FORM_SEND_BUTTON = (By.CSS_SELECTOR, ".register_button")
    ACCOUNT_HEADER = (By.CSS_SELECTOR, "span.hidden-xs")
